# Phiên bản của Docker Compose
version: '28.5.1'

# Nơi định nghĩa các dịch vụ (container)
services:
  # Tên dịch vụ, bạn có thể đặt tùy ý
  mysql-db:
    # Sử dụng image MySQL phiên bản 8.0.43-oraclelinux9 từ Docker Hub
    image: mysql:8.0.43-oraclelinux9

    # Tên của container sẽ được tạo ra
    container_name: mysql-dev-container

    # Khởi động lại container nếu nó bị dừng
    restart: unless-stopped

    # Cấu hình các biến môi trường cho MySQL
    environment:
      # Mật khẩu cho user 'root'
      MYSQL_ROOT_PASSWORD: root
      # Tên database sẽ được tự động tạo khi container khởi động lần đầu
      MYSQL_DATABASE: ev_cost_sharing_db

    # Ánh xạ cổng (port mapping)
    # Ánh xạ cổng 3306 của máy bạn vào cổng 3306 bên trong container
    ports:
      - "3307:3306"

    # Gắn kết volume để lưu trữ dữ liệu
    # Dữ liệu của MySQL sẽ được lưu vào volume tên là 'mysql-data'
    # Điều này đảm bảo bạn không mất dữ liệu mỗi khi khởi động lại container
    volumes:
      - mysql-data:/var/lib/mysql

# Khai báo volume được sử dụng ở trên
volumes:
  mysql-data: