## STAGE 1: BUILD
FROM maven:3.9.5-eclipse-temurin-21 AS build
WORKDIR /app
# Copy source code và file build project (pom.xml)
COPY pom.xml .
COPY src ./src
# Build file jar
RUN mvn clean package -DskipTests

## STAGE 2: RUN
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
# Copy file jar từ Stage 1
COPY --from=build /app/target/*.jar app.jar
# ... các lệnh khác
EXPOSE 8083
ENTRYPOINT ["java","-jar","app.jar"]